MHmag <- read.table("D://My Documents//UFL//simulation//irreversible//ismMHsimulation.txt",header=F)
MHmag.ts <- ts(MHmag[,2])
MHmag.acf <- acf(MHmag.ts)
plot(MHmag.acf)
plot(MHmag.ts)
LMHmag <- read.table("D://My Documents//UFL//simulation//irreversible//ismLMHsimulation.txt",header=F)
LMHmag.ts <- ts(LMHmag[,2])
LMHmag.acf <- acf(LMHmag.ts)
plot(LMHmag.ts)
GBmag <- read.table("D://My Documents//UFL//simulation//irreversible//ismGBsimulation.txt",header=F)
GBmag.ts <- ts(GBmag[,2])
GBmag.acf <- acf(GBmag.ts)
LMHmag2 <- read.table("D://My Documents//UFL//simulation//irreversible//ismLMHsimulation2.txt",header=F)
LMHmag2.ts <- ts(LMHmag2[,2])
LMHmag2.acf <- acf(LMHmag2.ts)
LMHmags <- read.table("D://My Documents//UFL//simulation//irreversible//ismLMHsimulation-s.txt",header=F)
LMHmag2s <- read.table("D://My Documents//UFL//simulation//irreversible//ismLMHsimulation2-s.txt",header=F)
MHmags <- read.table("D://My Documents//UFL//simulation//irreversible//ismMHsimulation-s.txt",header=F)
GBmags <-read.table("D://My Documents//UFL//simulation//irreversible//ismGBsimulations.txt",header=F)
MHmags.ts <- ts(MHmags[,2])
MHmags.acf <- acf(MHmags.ts)
LMHmag2s.ts <- ts(LMHmag2s[,2])
LMHmag2s.acf <- acf(LMHmag2s.ts)
LMHmags.ts <- ts(LMHmags[,2])
LMHmags.acf <- acf(LMHmags.ts)
GBmags.ts <- ts(GBmags[,2])
GBmags.acf <- acf(GBmags.ts)
